const specialties = [
  "Cardiologist",
  "Dermatologist",
  "General Physician",
  "Neurologist",
  "Psychiatrist",
  "Dentist",
  "Gastroenterologist",
  "Nephrologist",
  "Urologist",
  "Pulmonologist",
  "Endocrinologist",
  "Rheumatologist",
  "Oncologist",
  "Hematologist",
  "Immunologist",
  "Infectious Disease Specialist",
  "General Surgeon",
  "General Medicine",
  "Laparoscopic Surgeon",
  "Orthopedic Surgeon",
  "Neurosurgeon",
  "Plastic Surgeon",
  "Cardiothoracic Surgeon",
  "ENT Surgeon",
  "Vascular Surgeon",
  "Bariatric Surgeon",
  "Uro-Surgeon",
  "Colorectal Surgeon",
  "Surgical Oncologist",
  "Gynecologist/Obstetrician",
  "Pediatrician",
  "Neonatologist",
  "Fertility Specialist / IVF",
  "Lactation Consultant",
  "Ophthalmologist",
  "Diabetologist",
  "Geriatrician",
  "Pain Management Specialist",
  "Sleep Medicine Specialist",
  "Psychiatrist",
  "Psychologist",
  "Child Psychologist",
  "Clinical Psychologist",
  "Counsellor",
  "Occupational Therapist",
  "Physiotherapist",
  "Speech Therapist",
  "Audiologist",
  "Acupuncturist",
  "Chiropractor",
  "Prosthetist & Orthotist",
  "Dietitian / Nutritionist",
  "Wellness Coach",
  "Weight Management Specialist",
  "Ayurveda",
  "Homeopathy",
  "Siddha",
  "Unani",
  "Yoga & Naturopathy",
  "Acupressure Specialist",
  "Multi Speciality",
  "Other",
];

module.exports = specialties;
