const specialties = [
  "Cardiologist",
  "Dermatologist",
  "Dentist",
  "ENT",
  "Neurologist",
  "Pediatrician",
  "Orthopedic Surgeon",
  "Gynecologist",
  "Ophthalmologist",
  "Psychiatrist",
  "Endocrinologist",
  "Oncologist",
  "Urologist",
  "Gastroenterologist",
  "Pulmonologist",
  "Rheumatologist",
  "Allergist",
  "Ayurvedic",
  "Homoeopathic",
  "Unani",
  "Other",
];

module.exports = specialties;
